import { StudentRecord, StudentInput } from './types';
import { predictStudentPerformance } from './mlModel';

export interface ScenarioPreset {
  id: string;
  name: string;
  description: string;
  badge: string;
  badgeColor: string;
  data: StudentInput;
}

export const PRESET_SCENARIOS: ScenarioPreset[] = [
  {
    id: 'preset-high-achiever',
    name: 'High Honors Student',
    description: 'Outstanding attendance (96%), 32 study hrs/week, high sleep, top prior score.',
    badge: 'Expected Pass (90%+)',
    badgeColor: 'bg-emerald-100 text-emerald-800 border-emerald-300',
    data: {
      studentId: 'STU-1001',
      studentName: 'Alexander Price',
      attendanceRate: 96.5,
      weeklyStudyHours: 32,
      previousSemesterScore: 92.5,
      sleepHoursPerNight: 8.5,
      extracurricularActivities: 1,
      parentalEducationLevel: 2,
      internetAccessAtHome: 1,
      partTimeJob: 0,
      learningDisability: 0,
    },
  },
  {
    id: 'preset-average-pass',
    name: 'Solid Passing Candidate',
    description: 'Standard 82% attendance, 18 hrs revision, prior semester 68%, normal sleep.',
    badge: 'Expected Pass (68-72%)',
    badgeColor: 'bg-teal-100 text-teal-800 border-teal-300',
    data: {
      studentId: 'STU-1002',
      studentName: 'Maya Patel',
      attendanceRate: 84.0,
      weeklyStudyHours: 18,
      previousSemesterScore: 68.0,
      sleepHoursPerNight: 7.0,
      extracurricularActivities: 0,
      parentalEducationLevel: 1,
      internetAccessAtHome: 1,
      partTimeJob: 0,
      learningDisability: 0,
    },
  },
  {
    id: 'preset-borderline-risk',
    name: 'Borderline Risk (<50 Threshold)',
    description: 'Attendance 62%, only 8 study hrs, prior score 54%, working part-time job.',
    badge: 'At Risk / Borderline (~47-50%)',
    badgeColor: 'bg-amber-100 text-amber-800 border-amber-300',
    data: {
      studentId: 'STU-004',
      studentName: 'Sofia Thomas',
      attendanceRate: 58.0,
      weeklyStudyHours: 12,
      previousSemesterScore: 54.0,
      sleepHoursPerNight: 5.5,
      extracurricularActivities: 0,
      parentalEducationLevel: 1,
      internetAccessAtHome: 1,
      partTimeJob: 1,
      learningDisability: 0,
    },
  },
  {
    id: 'preset-severe-fail',
    name: 'Critical At-Risk Case',
    description: 'Low attendance (52%), 2 study hrs/week, low sleep, heavy part-time job.',
    badge: 'Expected Fail (~34%)',
    badgeColor: 'bg-rose-100 text-rose-800 border-rose-300',
    data: {
      studentId: 'STU-006',
      studentName: 'Lucas Vance',
      attendanceRate: 52.0,
      weeklyStudyHours: 3,
      previousSemesterScore: 42.0,
      sleepHoursPerNight: 4.5,
      extracurricularActivities: 0,
      parentalEducationLevel: 0,
      internetAccessAtHome: 0,
      partTimeJob: 1,
      learningDisability: 1,
    },
  },
];

export const INITIAL_BENCHMARK_STUDENTS: StudentRecord[] = [
  {
    id: 'bench-1',
    studentId: 'STU-001',
    studentName: 'Sofia Harris',
    attendanceRate: 89.93,
    weeklyStudyHours: 32,
    previousSemesterScore: 89.81,
    sleepHoursPerNight: 4.0,
    extracurricularActivities: 0,
    parentalEducationLevel: 1,
    internetAccessAtHome: 1,
    partTimeJob: 0,
    learningDisability: 0,
    createdAt: '2026-09-20T09:15:00Z',
    prediction: predictStudentPerformance({
      studentId: 'STU-001',
      studentName: 'Sofia Harris',
      attendanceRate: 89.93,
      weeklyStudyHours: 32,
      previousSemesterScore: 89.81,
      sleepHoursPerNight: 4.0,
      extracurricularActivities: 0,
      parentalEducationLevel: 1,
      internetAccessAtHome: 1,
      partTimeJob: 0,
      learningDisability: 0,
    }),
  },
  {
    id: 'bench-2',
    studentId: 'STU-006',
    studentName: 'Lucas Vance',
    attendanceRate: 45.50,
    weeklyStudyHours: 5,
    previousSemesterScore: 34.57,
    sleepHoursPerNight: 4.5,
    extracurricularActivities: 0,
    parentalEducationLevel: 0,
    internetAccessAtHome: 1,
    partTimeJob: 1,
    learningDisability: 0,
    createdAt: '2026-09-20T09:45:00Z',
    prediction: predictStudentPerformance({
      studentId: 'STU-006',
      studentName: 'Lucas Vance',
      attendanceRate: 45.50,
      weeklyStudyHours: 5,
      previousSemesterScore: 34.57,
      sleepHoursPerNight: 4.5,
      extracurricularActivities: 0,
      parentalEducationLevel: 0,
      internetAccessAtHome: 1,
      partTimeJob: 1,
      learningDisability: 0,
    }),
  },
  {
    id: 'bench-3',
    studentId: 'STU-003',
    studentName: 'Ava Gupta',
    attendanceRate: 92.84,
    weeklyStudyHours: 33,
    previousSemesterScore: 58.28,
    sleepHoursPerNight: 9.0,
    extracurricularActivities: 0,
    parentalEducationLevel: 0,
    internetAccessAtHome: 1,
    partTimeJob: 1,
    learningDisability: 0,
    createdAt: '2026-09-20T10:30:00Z',
    prediction: predictStudentPerformance({
      studentId: 'STU-003',
      studentName: 'Ava Gupta',
      attendanceRate: 92.84,
      weeklyStudyHours: 33,
      previousSemesterScore: 58.28,
      sleepHoursPerNight: 9.0,
      extracurricularActivities: 0,
      parentalEducationLevel: 0,
      internetAccessAtHome: 1,
      partTimeJob: 1,
      learningDisability: 0,
    }),
  },
  {
    id: 'bench-4',
    studentId: 'STU-943',
    studentName: 'Liam Cooper',
    attendanceRate: 51.20,
    weeklyStudyHours: 8,
    previousSemesterScore: 45.22,
    sleepHoursPerNight: 5.5,
    extracurricularActivities: 0,
    parentalEducationLevel: 1,
    internetAccessAtHome: 0,
    partTimeJob: 1,
    learningDisability: 0,
    createdAt: '2026-09-20T11:15:00Z',
    prediction: predictStudentPerformance({
      studentId: 'STU-943',
      studentName: 'Liam Cooper',
      attendanceRate: 51.20,
      weeklyStudyHours: 8,
      previousSemesterScore: 45.22,
      sleepHoursPerNight: 5.5,
      extracurricularActivities: 0,
      parentalEducationLevel: 1,
      internetAccessAtHome: 0,
      partTimeJob: 1,
      learningDisability: 0,
    }),
  },
  {
    id: 'bench-5',
    studentId: 'STU-004',
    studentName: 'Sofia Thomas',
    attendanceRate: 55.88,
    weeklyStudyHours: 39,
    previousSemesterScore: 55.87,
    sleepHoursPerNight: 5.5,
    extracurricularActivities: 0,
    parentalEducationLevel: 1,
    internetAccessAtHome: 1,
    partTimeJob: 1,
    learningDisability: 0,
    createdAt: '2026-09-20T11:45:00Z',
    prediction: predictStudentPerformance({
      studentId: 'STU-004',
      studentName: 'Sofia Thomas',
      attendanceRate: 55.88,
      weeklyStudyHours: 39,
      previousSemesterScore: 55.87,
      sleepHoursPerNight: 5.5,
      extracurricularActivities: 0,
      parentalEducationLevel: 1,
      internetAccessAtHome: 1,
      partTimeJob: 1,
      learningDisability: 0,
    }),
  },
  {
    id: 'bench-6',
    studentId: 'STU-999',
    studentName: 'Emily Wright',
    attendanceRate: 54.10,
    weeklyStudyHours: 9,
    previousSemesterScore: 42.46,
    sleepHoursPerNight: 5.0,
    extracurricularActivities: 0,
    parentalEducationLevel: 0,
    internetAccessAtHome: 1,
    partTimeJob: 1,
    learningDisability: 0,
    createdAt: '2026-09-20T13:20:00Z',
    prediction: predictStudentPerformance({
      studentId: 'STU-999',
      studentName: 'Emily Wright',
      attendanceRate: 54.10,
      weeklyStudyHours: 9,
      previousSemesterScore: 42.46,
      sleepHoursPerNight: 5.0,
      extracurricularActivities: 0,
      parentalEducationLevel: 0,
      internetAccessAtHome: 1,
      partTimeJob: 1,
      learningDisability: 0,
    }),
  },
  {
    id: 'bench-7',
    studentId: 'STU-005',
    studentName: 'Mason Rodriguez',
    attendanceRate: 86.99,
    weeklyStudyHours: 10,
    previousSemesterScore: 56.79,
    sleepHoursPerNight: 8.0,
    extracurricularActivities: 1,
    parentalEducationLevel: 2,
    internetAccessAtHome: 1,
    partTimeJob: 0,
    learningDisability: 0,
    createdAt: '2026-09-20T14:10:00Z',
    prediction: predictStudentPerformance({
      studentId: 'STU-005',
      studentName: 'Mason Rodriguez',
      attendanceRate: 86.99,
      weeklyStudyHours: 10,
      previousSemesterScore: 56.79,
      sleepHoursPerNight: 8.0,
      extracurricularActivities: 1,
      parentalEducationLevel: 2,
      internetAccessAtHome: 1,
      partTimeJob: 0,
      learningDisability: 0,
    }),
  },
  {
    id: 'bench-8',
    studentId: 'STU-997',
    studentName: 'Evelyn Hill',
    attendanceRate: 60.20,
    weeklyStudyHours: 33,
    previousSemesterScore: 60.35,
    sleepHoursPerNight: 9.0,
    extracurricularActivities: 1,
    parentalEducationLevel: 1,
    internetAccessAtHome: 0,
    partTimeJob: 0,
    learningDisability: 0,
    createdAt: '2026-09-21T07:20:00Z',
    prediction: predictStudentPerformance({
      studentId: 'STU-997',
      studentName: 'Evelyn Hill',
      attendanceRate: 60.20,
      weeklyStudyHours: 33,
      previousSemesterScore: 60.35,
      sleepHoursPerNight: 9.0,
      extracurricularActivities: 1,
      parentalEducationLevel: 1,
      internetAccessAtHome: 0,
      partTimeJob: 0,
      learningDisability: 0,
    }),
  },
  {
    id: 'bench-9',
    studentId: 'STU-998',
    studentName: 'Michael Lee',
    attendanceRate: 82.70,
    weeklyStudyHours: 9,
    previousSemesterScore: 72.68,
    sleepHoursPerNight: 5.0,
    extracurricularActivities: 1,
    parentalEducationLevel: 1,
    internetAccessAtHome: 1,
    partTimeJob: 0,
    learningDisability: 0,
    createdAt: '2026-09-21T07:45:00Z',
    prediction: predictStudentPerformance({
      studentId: 'STU-998',
      studentName: 'Michael Lee',
      attendanceRate: 82.70,
      weeklyStudyHours: 9,
      previousSemesterScore: 72.68,
      sleepHoursPerNight: 5.0,
      extracurricularActivities: 1,
      parentalEducationLevel: 1,
      internetAccessAtHome: 1,
      partTimeJob: 0,
      learningDisability: 0,
    }),
  },
  {
    id: 'bench-10',
    studentId: 'STU-1001',
    studentName: 'Mason Flores',
    attendanceRate: 95.58,
    weeklyStudyHours: 10,
    previousSemesterScore: 66.76,
    sleepHoursPerNight: 4.0,
    extracurricularActivities: 1,
    parentalEducationLevel: 0,
    internetAccessAtHome: 1,
    partTimeJob: 0,
    learningDisability: 0,
    createdAt: '2026-09-21T08:15:00Z',
    prediction: predictStudentPerformance({
      studentId: 'STU-1001',
      studentName: 'Mason Flores',
      attendanceRate: 95.58,
      weeklyStudyHours: 10,
      previousSemesterScore: 66.76,
      sleepHoursPerNight: 4.0,
      extracurricularActivities: 1,
      parentalEducationLevel: 0,
      internetAccessAtHome: 1,
      partTimeJob: 0,
      learningDisability: 0,
    }),
  },
];
